### ISSUE TITLE
Embedis EEPROM dictionary doen't work with SerialLink

### ISSUE THREAD

**Issue by juancreyes** [xoseperez/sonoffsc#11]
I have connected serial port to ESP8266 side and remove serial communication toward Atmega. I think Embedis seens doesn't work properly with SerialLink.h runing at same time. Tested "commands", "dictionary" and no lucky. However if I put serial terminal "AT+TEMP=230" I got success MQTT response ([MQTT] Sending /device/temperature 226.50).

If my diagnostic is right, Any ideas how to figure out a solution ?.

BR

**Comment by xoseperez** [comment]
Embedis commands are disabled because I did find they were not compatible with serial communication with the ATMega328. The parser is handled in the settingsLoop method which is not being called in the main loop.

**Comment by juancreyes** [comment]
Thanks for your feedback. It is physical limitation of having just one serial interface.
